// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Component from "./Component.bs.js";

function App(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("div", undefined, "My 4 Dollar Idea App"), React.createElement(Component.make, { }));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
