// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";

function Component(Props) {
  return React.createElement("div", undefined, "My 4 Dollar Idea Component!");
}

var make = Component;

export {
  make ,
  
}
/* react Not a pure module */
