// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as React from "react";
import * as ReactSsrPrepass from "react-ssr-prepass";

ReactSsrPrepass(React.createElement(App.make, { }));

ReactSsrPrepass(/* tuple */[
      React.createElement(App.make, { }),
      (function (element) {
          console.log("Element found: ", element);
          return undefined;
        })
    ]);

export {
  
}
/*  Not a pure module */
