// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as React from "react";
import * as ReactSsrPrepass from "react-ssr-prepass";

ReactSsrPrepass(React.createElement(App.make, { }));

ReactSsrPrepass(/* tuple */[
      React.createElement(App.make, { }),
      (function (element) {
          console.log("Element found: ", element);
          return undefined;
        })
    ]);

var prepass = ReactSsrPrepass(React.createElement(App.make, { }));

prepass.then((function (param) {
        console.log("Prepass has finished.");
        return Promise.resolve((function (param) {
                      return /* () */0;
                    }));
      }));

export {
  prepass ,
  
}
/*  Not a pure module */
